const FieldMaps = {
  button: {
    itemType: 'Button',
    attrs: [
      {
        label: "尺寸",
        key: "size",
        valueType: "select",
        valueList: ["medium", "small", "mini"],
        defaultValue: "",
      },
      {
        label: "类型",
        key: "type",
        valueType: "select",
        valueList: ["primary", "success", "warning", "danger", "info", "text"],
        defaultValue: "",
      },
      {
        label: "是否朴素按钮",
        key: "plain",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "是否圆角按钮",
        key: "round",
        defaultValue: false,
      },
      {
        label: "是否圆形按钮",
        key: "circle",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "是否加载中状态",
        key: "loading",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "是否禁用状态",
        key: "disabled",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "图标类名",
        key: "icon",
        valueType: "input",
        defaultValue: "",
      },
      {
        label: "是否默认聚焦",
        key: "autofocus",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "原生type属性",
        key: "native-type",
        valueType: "select",
        valueList: ["button", "submit", "reset"],
        defaultValue: "button",
      },
    ],
  },
  input: {
    itemType: 'Input',
    attrs: [
      {
        key: "type",
        label: "类型",
        valueType: "select",
        valueList: [
          "text",
          "button",
          "checkbox",
          "color",
          "date",
          "datetime-local",
          "email",
          "file",
          "hidden",
          "image",
          "month",
          "number",
          "password",
          "radio",
          "range",
          "reset",
          "submit",
          "tel",
          "time",
          "url",
          "week",
        ],
        default: "text",
      },
      {
        key: "value",
        label: "默认值",
        valueType: "input",
        defaultValue: "",
      },
      {
        key: "maxlength",
        label: "最大输入长度",
        valueType: "number",
      },
      {
        key: "minlength",
        label: "最小输入长度",
        valueType: "number",
      },
      {
        key: "show-word-limit",
        label: "	是否显示输入字数统计",
        valueType: "switch",
        defaultValue: false,
      },
      {
        key: "placeholder",
        label: "输入框占位文本",
        valueType: "input",
        defaultValue: "",
      },
      {
        key: "clearable",
        label: "是否可清空",
        valueType: "switch",
        defaultValue: "",
      },
      {
        key: "show-password",
        label: "是否显示切换密码图标",
        valueType: "switch",
        defaultValue: false,
      },
      {
        key: "disabled",
        label: "禁用",
        valueType: "switch",
        defaultValue: false,
      },
      {
        key: "size",
        label: "尺寸",
        valueType: "select",
        valueList: ["medium", "small", "mini"],
      },
      {
        key: "prefix-icon",
        label: "输入框头部图标",
        valueType: "input",
        defaultValue: "",
      },
      {
        key: "suffix-icon",
        label: "输入框尾部图标",
        valueType: "input",
        defaultValue: "",
      },
      {
        key: "rows",
        label: "输入框行数",
        valueType: "number",
        defaultValue: 2,
      },
      {
        key: "autosize",
        label: "自适应内容高度",
        valueType: "switch",
        defaultValue: false,
      },
      {
        key: "autocomplete",
        label: "自动补全",
        valueType: "switch",
        defaultValue: false,
      },
      { key: "name", label: "	原生属性", valueType: "input", defaultValue: "" },
      {
        key: "readonly",
        label: "是否只读",
        valueType: "switch",
        defaultValue: false,
      },
      { key: "max", label: "设置最大值", valueType: "" },
      { key: "min", label: "设置最小值", valueType: "" },
      {
        key: "step",
        label: "数字间隔",
        valueType: "number",
      },
      {
        key: "resize",
        label: "	控制是否能被用户缩放",
        valueType: "	string	none, both, horizontal, vertical	—",
      },
      {
        key: "autofocus",
        label: "自动获取焦点",
        valueType: "switch",
        defaultValue: false,
      },
      {
        key: "label",
        label: "label文字",
        valueType: "input",
        defaultValue: "",
      },
    ],
  },
  radio: {
    itemType: 'Radio',
    attrs: [
      {
        label: "默认值",
        key: "value",
        valueType: "input",
        defaultValue: "",
      },
      {
        label: "label",
        key: "label",
        valueType: "input",
        defaultValue: "",
      },
      {
        label: "是否禁用",
        key: "disabled",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "是否显示边框",
        key: "border",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "尺寸",
        key: "size",
        valueType: "select",
        valueList: ["medium", "small", "mini"],
        defaultValue: "",
      },
      {
        label: "name",
        key: "name",
        valueType: "input",
        defaultValue: "",
      },
    ],
  },
  switch: {
    itemType: 'Switch',
    attrs: [
      {
        label: "默认值",
        key: "value",
        valueType: "input",
        defaultValue: "",
      },
      {
        label: "label",
        key: "label",
        valueType: "input",
        defaultValue: "",
      },
      {
        label: "是否禁用",
        key: "disabled",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "是否显示边框",
        key: "border",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "尺寸",
        key: "size",
        valueType: "select",
        valueList: ["medium", "small", "mini"],
        defaultValue: "",
      },
      {
        label: "name",
        key: "name",
        valueType: "input",
        defaultValue: "",
      },
    ],
  },
  checkbox: {
    itemType: 'Check',
    attrs: [
      {
        label: "默认值",
        key: "value",
        valueType: "input",
        defaultValue: "",
      },
      {
        label: "label",
        key: "label",
        valueType: "input",
        defaultValue: "",
      },
      {
        label: "是否禁用",
        key: "disabled",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "是否显示边框",
        key: "border",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "尺寸",
        key: "size",
        valueType: "select",
        valueList: ["medium", "small", "mini"],
        defaultValue: "",
      },
      {
        label: "name",
        key: "name",
        valueType: "input",
        defaultValue: "",
      },
    ],
  },
  select: {
    itemType: 'Select',
    attrs: [
      {
        label: "默认值",
        key: "value",
        valueType: "input",
        defaultValue: "",
      },
      {
        label: "label",
        key: "label",
        valueType: "input",
        defaultValue: "",
      },
      {
        label: "是否禁用",
        key: "disabled",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "是否显示边框",
        key: "border",
        valueType: "switch",
        defaultValue: false,
      },
      {
        label: "尺寸",
        key: "size",
        valueType: "select",
        valueList: ["medium", "small", "mini"],
        defaultValue: "",
      },
      {
        label: "name",
        key: "name",
        valueType: "input",
        defaultValue: "",
      },
    ],
  },
};
export default FieldMaps;
